// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductHistory.proto

package com.in.ProductHistory;

public final class ProductHistory {
  private ProductHistory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecentlyViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecentlyViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecentlyViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecentlyViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRecentViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRecentViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRecentViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRecentViewResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProductHistory.proto\"%\n\023RecentlyViewRe" +
      "quest\022\016\n\006userId\030\001 \001(\t\"*\n\024RecentlyViewRes" +
      "ponse\022\022\n\nProductIds\030\001 \003(\t\"<\n\027UpdateRecen" +
      "tViewRequest\022\016\n\006userId\030\001 \001(\t\022\021\n\tproductI" +
      "d\030\002 \001(\t\"*\n\030UpdateRecentViewResponse\022\016\n\006s" +
      "tatus\030\001 \001(\0102\264\001\n\023RecentlyViewService\022I\n\032f" +
      "etchRecentlyViewedHistory\022\024.RecentlyView" +
      "Request\032\025.RecentlyViewResponse\022R\n\033update" +
      "dRecentlyViewProducts\022\030.UpdateRecentView" +
      "Request\032\031.UpdateRecentViewResponseB\031\n\025co" +
      "m.in.ProductHistoryP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RecentlyViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecentlyViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecentlyViewRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_RecentlyViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecentlyViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecentlyViewResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
    internal_static_UpdateRecentViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateRecentViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRecentViewRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_UpdateRecentViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateRecentViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRecentViewResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
