// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductHistory.proto

package com.in.ProductHistory;

/**
 * Protobuf type {@code RecentlyViewResponse}
 */
public  final class RecentlyViewResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RecentlyViewResponse)
    RecentlyViewResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecentlyViewResponse.newBuilder() to construct.
  private RecentlyViewResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecentlyViewResponse() {
    productIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecentlyViewResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              productIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            productIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        productIds_ = productIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.in.ProductHistory.ProductHistory.internal_static_RecentlyViewResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.in.ProductHistory.ProductHistory.internal_static_RecentlyViewResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.in.ProductHistory.RecentlyViewResponse.class, com.in.ProductHistory.RecentlyViewResponse.Builder.class);
  }

  public static final int PRODUCTIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList productIds_;
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getProductIdsList() {
    return productIds_;
  }
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  public int getProductIdsCount() {
    return productIds_.size();
  }
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  public java.lang.String getProductIds(int index) {
    return productIds_.get(index);
  }
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProductIdsBytes(int index) {
    return productIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < productIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < productIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(productIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getProductIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.in.ProductHistory.RecentlyViewResponse)) {
      return super.equals(obj);
    }
    com.in.ProductHistory.RecentlyViewResponse other = (com.in.ProductHistory.RecentlyViewResponse) obj;

    boolean result = true;
    result = result && getProductIdsList()
        .equals(other.getProductIdsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductIdsCount() > 0) {
      hash = (37 * hash) + PRODUCTIDS_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.in.ProductHistory.RecentlyViewResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.in.ProductHistory.RecentlyViewResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RecentlyViewResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RecentlyViewResponse)
      com.in.ProductHistory.RecentlyViewResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.in.ProductHistory.ProductHistory.internal_static_RecentlyViewResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.in.ProductHistory.ProductHistory.internal_static_RecentlyViewResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.in.ProductHistory.RecentlyViewResponse.class, com.in.ProductHistory.RecentlyViewResponse.Builder.class);
    }

    // Construct using com.in.ProductHistory.RecentlyViewResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.in.ProductHistory.ProductHistory.internal_static_RecentlyViewResponse_descriptor;
    }

    @java.lang.Override
    public com.in.ProductHistory.RecentlyViewResponse getDefaultInstanceForType() {
      return com.in.ProductHistory.RecentlyViewResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.in.ProductHistory.RecentlyViewResponse build() {
      com.in.ProductHistory.RecentlyViewResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.in.ProductHistory.RecentlyViewResponse buildPartial() {
      com.in.ProductHistory.RecentlyViewResponse result = new com.in.ProductHistory.RecentlyViewResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        productIds_ = productIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productIds_ = productIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.in.ProductHistory.RecentlyViewResponse) {
        return mergeFrom((com.in.ProductHistory.RecentlyViewResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.in.ProductHistory.RecentlyViewResponse other) {
      if (other == com.in.ProductHistory.RecentlyViewResponse.getDefaultInstance()) return this;
      if (!other.productIds_.isEmpty()) {
        if (productIds_.isEmpty()) {
          productIds_ = other.productIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductIdsIsMutable();
          productIds_.addAll(other.productIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.in.ProductHistory.RecentlyViewResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.in.ProductHistory.RecentlyViewResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList productIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureProductIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        productIds_ = new com.google.protobuf.LazyStringArrayList(productIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdsList() {
      return productIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public java.lang.String getProductIds(int index) {
      return productIds_.get(index);
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdsBytes(int index) {
      return productIds_.getByteString(index);
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public Builder setProductIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureProductIdsIsMutable();
      productIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public Builder addProductIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureProductIdsIsMutable();
      productIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public Builder addAllProductIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureProductIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public Builder clearProductIds() {
      productIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ProductIds = 1;</code>
     */
    public Builder addProductIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureProductIdsIsMutable();
      productIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RecentlyViewResponse)
  }

  // @@protoc_insertion_point(class_scope:RecentlyViewResponse)
  private static final com.in.ProductHistory.RecentlyViewResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.in.ProductHistory.RecentlyViewResponse();
  }

  public static com.in.ProductHistory.RecentlyViewResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecentlyViewResponse>
      PARSER = new com.google.protobuf.AbstractParser<RecentlyViewResponse>() {
    @java.lang.Override
    public RecentlyViewResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecentlyViewResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecentlyViewResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecentlyViewResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.in.ProductHistory.RecentlyViewResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

