// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductHistory.proto

package com.in.ProductHistory;

public interface RecentlyViewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecentlyViewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  java.util.List<java.lang.String>
      getProductIdsList();
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  int getProductIdsCount();
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  java.lang.String getProductIds(int index);
  /**
   * <code>repeated string ProductIds = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdsBytes(int index);
}
