// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.in.Session;

public interface CreateSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string deviceType = 2;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <code>string deviceType = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>string sessionId = 3;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
