// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.in.Session;

public interface CreateSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
