// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.in.Session;

public interface SessionStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SessionStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isActive = 1;</code>
   */
  boolean getIsActive();

  /**
   * <code>string userId = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string deviceType = 3;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <code>string deviceType = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();
}
