// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.in.proto;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniqueEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniqueEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniqueEmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniqueEmailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerifyCredentialsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerifyCredentialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerifyCredentialsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerifyCredentialsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"w\n\023RegisterUserRequest\022\016\n\006u" +
      "serId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t" +
      "\022\024\n\014mobileNumber\030\004 \001(\t\022\013\n\003dob\030\005 \001(\t\022\020\n\010p" +
      "assword\030\006 \001(\t\"8\n\024RegisterUserResponse\022\017\n" +
      "\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"#\n\022Uniqu" +
      "eEmailRequest\022\r\n\005email\030\001 \001(\t\"\'\n\023UniqueEm" +
      "ailResponse\022\020\n\010isUnique\030\001 \001(\010\"2\n\017Passwor" +
      "dRequest\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(" +
      "\t\"#\n\020PasswordResponse\022\017\n\007message\030\001 \001(\t\"*" +
      "\n\030VerifyCredentialsRequest\022\016\n\006userId\030\001 \001" +
      "(\t\"K\n\031VerifyCredentialsResponse\022\016\n\006userI" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t2" +
      "\326\002\n\017UserDataService\022;\n\014RegisterUser\022\024.Re" +
      "gisterUserRequest\032\025.RegisterUserResponse" +
      "\022G\n\032verifyEmailAddressIsUnique\022\023.UniqueE" +
      "mailRequest\032\024.UniqueEmailResponse\022;\n\016isE" +
      "mailPresent\022\023.UniqueEmailRequest\032\024.Uniqu" +
      "eEmailResponse\0224\n\rresetPassword\022\020.Passwo" +
      "rdRequest\032\021.PasswordResponse\022J\n\021VerifyCr" +
      "edentials\022\031.VerifyCredentialsRequest\032\032.V" +
      "erifyCredentialsResponseB\020\n\014com.in.proto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegisterUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Email", "MobileNumber", "Dob", "Password", });
    internal_static_RegisterUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RegisterUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_UniqueEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UniqueEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniqueEmailRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_UniqueEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UniqueEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniqueEmailResponse_descriptor,
        new java.lang.String[] { "IsUnique", });
    internal_static_PasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_PasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_VerifyCredentialsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_VerifyCredentialsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerifyCredentialsRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_VerifyCredentialsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_VerifyCredentialsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerifyCredentialsResponse_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
