// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartDetails.proto

package com.in.cart;

public final class CartDetails {
  private CartDetails() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CartProductDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CartProductDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveProductDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveProductDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewCartProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewCartProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CartProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CartProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewCartProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewCartProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CartDetails.proto\032\033google/protobuf/emp" +
      "ty.proto\"J\n\026CartProductDataRequest\022\016\n\006us" +
      "erId\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t\022\r\n\005count\030\003" +
      " \001(\005\"=\n\030RemoveProductDataRequest\022\016\n\006user" +
      "Id\030\001 \001(\t\022\021\n\tproductId\030\002 \001(\t\"(\n\026ViewCartP" +
      "roductRequest\022\016\n\006userId\030\001 \001(\t\"\231\001\n\013CartPr" +
      "oduct\022\021\n\tproductId\030\001 \001(\t\022\022\n\ncategoryId\030\002" +
      " \001(\t\022\023\n\013productName\030\003 \001(\t\022\023\n\013productDesc" +
      "\030\004 \001(\t\022\024\n\014productPrice\030\005 \001(\001\022\021\n\timagePat" +
      "h\030\006 \001(\t\022\020\n\010quantity\030\007 \001(\005\"8\n\027ViewCartPro" +
      "ductResponse\022\035\n\007product\030\001 \003(\0132\014.CartProd" +
      "uct2\214\003\n\026CartDataProductService\022C\n\020addPro" +
      "ductToCart\022\027.CartProductDataRequest\032\026.go" +
      "ogle.protobuf.Empty\022R\n\037decreaseQuantityO" +
      "fProductToCart\022\027.CartProductDataRequest\032" +
      "\026.google.protobuf.Empty\022J\n\025removeProduct" +
      "FromCart\022\031.RemoveProductDataRequest\032\026.go" +
      "ogle.protobuf.Empty\022G\n\022fetchCartOfProduc" +
      "t\022\027.ViewCartProductRequest\032\030.ViewCartPro" +
      "ductResponse\022D\n\021saveCartOfProduct\022\027.View" +
      "CartProductRequest\032\026.google.protobuf.Emp" +
      "tyB\017\n\013com.in.cartP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_CartProductDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CartProductDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CartProductDataRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", "Count", });
    internal_static_RemoveProductDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RemoveProductDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveProductDataRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductId", });
    internal_static_ViewCartProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ViewCartProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ViewCartProductRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_CartProduct_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CartProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CartProduct_descriptor,
        new java.lang.String[] { "ProductId", "CategoryId", "ProductName", "ProductDesc", "ProductPrice", "ImagePath", "Quantity", });
    internal_static_ViewCartProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ViewCartProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ViewCartProductResponse_descriptor,
        new java.lang.String[] { "Product", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
