// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartDetails.proto

package com.in.cart;

public interface CartProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string categoryId = 2;</code>
   */
  java.lang.String getCategoryId();
  /**
   * <code>string categoryId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string productName = 3;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productDesc = 4;</code>
   */
  java.lang.String getProductDesc();
  /**
   * <code>string productDesc = 4;</code>
   */
  com.google.protobuf.ByteString
      getProductDescBytes();

  /**
   * <code>double productPrice = 5;</code>
   */
  double getProductPrice();

  /**
   * <code>string imagePath = 6;</code>
   */
  java.lang.String getImagePath();
  /**
   * <code>string imagePath = 6;</code>
   */
  com.google.protobuf.ByteString
      getImagePathBytes();

  /**
   * <code>int32 quantity = 7;</code>
   */
  int getQuantity();
}
