// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dashboard.proto

package com.in.dashboard;

public interface DashboardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DashboardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DashboardDetails dashBoardDetails = 1;</code>
   */
  boolean hasDashBoardDetails();
  /**
   * <code>.DashboardDetails dashBoardDetails = 1;</code>
   */
  com.in.dashboard.DashboardDetails getDashBoardDetails();
  /**
   * <code>.DashboardDetails dashBoardDetails = 1;</code>
   */
  com.in.dashboard.DashboardDetailsOrBuilder getDashBoardDetailsOrBuilder();
}
