// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dashboard.proto

package com.in.dashboard;

/**
 * Protobuf type {@code DashboardDetails}
 */
public  final class DashboardDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DashboardDetails)
    DashboardDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DashboardDetails.newBuilder() to construct.
  private DashboardDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DashboardDetails() {
    featuredProducts_ = java.util.Collections.emptyList();
    similarProducts_ = java.util.Collections.emptyList();
    recentlyViewedProducts_ = java.util.Collections.emptyList();
    categories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DashboardDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              featuredProducts_ = new java.util.ArrayList<com.in.dashboard.Product>();
              mutable_bitField0_ |= 0x00000001;
            }
            featuredProducts_.add(
                input.readMessage(com.in.dashboard.Product.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              similarProducts_ = new java.util.ArrayList<com.in.dashboard.Product>();
              mutable_bitField0_ |= 0x00000002;
            }
            similarProducts_.add(
                input.readMessage(com.in.dashboard.Product.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              recentlyViewedProducts_ = new java.util.ArrayList<com.in.dashboard.Product>();
              mutable_bitField0_ |= 0x00000004;
            }
            recentlyViewedProducts_.add(
                input.readMessage(com.in.dashboard.Product.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              categories_ = new java.util.ArrayList<com.in.dashboard.Category>();
              mutable_bitField0_ |= 0x00000008;
            }
            categories_.add(
                input.readMessage(com.in.dashboard.Category.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        featuredProducts_ = java.util.Collections.unmodifiableList(featuredProducts_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        similarProducts_ = java.util.Collections.unmodifiableList(similarProducts_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        recentlyViewedProducts_ = java.util.Collections.unmodifiableList(recentlyViewedProducts_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        categories_ = java.util.Collections.unmodifiableList(categories_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.in.dashboard.Dashboard.internal_static_DashboardDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.in.dashboard.Dashboard.internal_static_DashboardDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.in.dashboard.DashboardDetails.class, com.in.dashboard.DashboardDetails.Builder.class);
  }

  public static final int FEATUREDPRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<com.in.dashboard.Product> featuredProducts_;
  /**
   * <code>repeated .Product featuredProducts = 1;</code>
   */
  public java.util.List<com.in.dashboard.Product> getFeaturedProductsList() {
    return featuredProducts_;
  }
  /**
   * <code>repeated .Product featuredProducts = 1;</code>
   */
  public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
      getFeaturedProductsOrBuilderList() {
    return featuredProducts_;
  }
  /**
   * <code>repeated .Product featuredProducts = 1;</code>
   */
  public int getFeaturedProductsCount() {
    return featuredProducts_.size();
  }
  /**
   * <code>repeated .Product featuredProducts = 1;</code>
   */
  public com.in.dashboard.Product getFeaturedProducts(int index) {
    return featuredProducts_.get(index);
  }
  /**
   * <code>repeated .Product featuredProducts = 1;</code>
   */
  public com.in.dashboard.ProductOrBuilder getFeaturedProductsOrBuilder(
      int index) {
    return featuredProducts_.get(index);
  }

  public static final int SIMILARPRODUCTS_FIELD_NUMBER = 2;
  private java.util.List<com.in.dashboard.Product> similarProducts_;
  /**
   * <code>repeated .Product similarProducts = 2;</code>
   */
  public java.util.List<com.in.dashboard.Product> getSimilarProductsList() {
    return similarProducts_;
  }
  /**
   * <code>repeated .Product similarProducts = 2;</code>
   */
  public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
      getSimilarProductsOrBuilderList() {
    return similarProducts_;
  }
  /**
   * <code>repeated .Product similarProducts = 2;</code>
   */
  public int getSimilarProductsCount() {
    return similarProducts_.size();
  }
  /**
   * <code>repeated .Product similarProducts = 2;</code>
   */
  public com.in.dashboard.Product getSimilarProducts(int index) {
    return similarProducts_.get(index);
  }
  /**
   * <code>repeated .Product similarProducts = 2;</code>
   */
  public com.in.dashboard.ProductOrBuilder getSimilarProductsOrBuilder(
      int index) {
    return similarProducts_.get(index);
  }

  public static final int RECENTLYVIEWEDPRODUCTS_FIELD_NUMBER = 3;
  private java.util.List<com.in.dashboard.Product> recentlyViewedProducts_;
  /**
   * <code>repeated .Product recentlyViewedProducts = 3;</code>
   */
  public java.util.List<com.in.dashboard.Product> getRecentlyViewedProductsList() {
    return recentlyViewedProducts_;
  }
  /**
   * <code>repeated .Product recentlyViewedProducts = 3;</code>
   */
  public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
      getRecentlyViewedProductsOrBuilderList() {
    return recentlyViewedProducts_;
  }
  /**
   * <code>repeated .Product recentlyViewedProducts = 3;</code>
   */
  public int getRecentlyViewedProductsCount() {
    return recentlyViewedProducts_.size();
  }
  /**
   * <code>repeated .Product recentlyViewedProducts = 3;</code>
   */
  public com.in.dashboard.Product getRecentlyViewedProducts(int index) {
    return recentlyViewedProducts_.get(index);
  }
  /**
   * <code>repeated .Product recentlyViewedProducts = 3;</code>
   */
  public com.in.dashboard.ProductOrBuilder getRecentlyViewedProductsOrBuilder(
      int index) {
    return recentlyViewedProducts_.get(index);
  }

  public static final int CATEGORIES_FIELD_NUMBER = 4;
  private java.util.List<com.in.dashboard.Category> categories_;
  /**
   * <code>repeated .Category categories = 4;</code>
   */
  public java.util.List<com.in.dashboard.Category> getCategoriesList() {
    return categories_;
  }
  /**
   * <code>repeated .Category categories = 4;</code>
   */
  public java.util.List<? extends com.in.dashboard.CategoryOrBuilder> 
      getCategoriesOrBuilderList() {
    return categories_;
  }
  /**
   * <code>repeated .Category categories = 4;</code>
   */
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <code>repeated .Category categories = 4;</code>
   */
  public com.in.dashboard.Category getCategories(int index) {
    return categories_.get(index);
  }
  /**
   * <code>repeated .Category categories = 4;</code>
   */
  public com.in.dashboard.CategoryOrBuilder getCategoriesOrBuilder(
      int index) {
    return categories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < featuredProducts_.size(); i++) {
      output.writeMessage(1, featuredProducts_.get(i));
    }
    for (int i = 0; i < similarProducts_.size(); i++) {
      output.writeMessage(2, similarProducts_.get(i));
    }
    for (int i = 0; i < recentlyViewedProducts_.size(); i++) {
      output.writeMessage(3, recentlyViewedProducts_.get(i));
    }
    for (int i = 0; i < categories_.size(); i++) {
      output.writeMessage(4, categories_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < featuredProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, featuredProducts_.get(i));
    }
    for (int i = 0; i < similarProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, similarProducts_.get(i));
    }
    for (int i = 0; i < recentlyViewedProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, recentlyViewedProducts_.get(i));
    }
    for (int i = 0; i < categories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, categories_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.in.dashboard.DashboardDetails)) {
      return super.equals(obj);
    }
    com.in.dashboard.DashboardDetails other = (com.in.dashboard.DashboardDetails) obj;

    boolean result = true;
    result = result && getFeaturedProductsList()
        .equals(other.getFeaturedProductsList());
    result = result && getSimilarProductsList()
        .equals(other.getSimilarProductsList());
    result = result && getRecentlyViewedProductsList()
        .equals(other.getRecentlyViewedProductsList());
    result = result && getCategoriesList()
        .equals(other.getCategoriesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFeaturedProductsCount() > 0) {
      hash = (37 * hash) + FEATUREDPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getFeaturedProductsList().hashCode();
    }
    if (getSimilarProductsCount() > 0) {
      hash = (37 * hash) + SIMILARPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getSimilarProductsList().hashCode();
    }
    if (getRecentlyViewedProductsCount() > 0) {
      hash = (37 * hash) + RECENTLYVIEWEDPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getRecentlyViewedProductsList().hashCode();
    }
    if (getCategoriesCount() > 0) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + getCategoriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.in.dashboard.DashboardDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.in.dashboard.DashboardDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.in.dashboard.DashboardDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.in.dashboard.DashboardDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.in.dashboard.DashboardDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DashboardDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DashboardDetails)
      com.in.dashboard.DashboardDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.in.dashboard.Dashboard.internal_static_DashboardDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.in.dashboard.Dashboard.internal_static_DashboardDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.in.dashboard.DashboardDetails.class, com.in.dashboard.DashboardDetails.Builder.class);
    }

    // Construct using com.in.dashboard.DashboardDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFeaturedProductsFieldBuilder();
        getSimilarProductsFieldBuilder();
        getRecentlyViewedProductsFieldBuilder();
        getCategoriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (featuredProductsBuilder_ == null) {
        featuredProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        featuredProductsBuilder_.clear();
      }
      if (similarProductsBuilder_ == null) {
        similarProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        similarProductsBuilder_.clear();
      }
      if (recentlyViewedProductsBuilder_ == null) {
        recentlyViewedProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        recentlyViewedProductsBuilder_.clear();
      }
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        categoriesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.in.dashboard.Dashboard.internal_static_DashboardDetails_descriptor;
    }

    @java.lang.Override
    public com.in.dashboard.DashboardDetails getDefaultInstanceForType() {
      return com.in.dashboard.DashboardDetails.getDefaultInstance();
    }

    @java.lang.Override
    public com.in.dashboard.DashboardDetails build() {
      com.in.dashboard.DashboardDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.in.dashboard.DashboardDetails buildPartial() {
      com.in.dashboard.DashboardDetails result = new com.in.dashboard.DashboardDetails(this);
      int from_bitField0_ = bitField0_;
      if (featuredProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          featuredProducts_ = java.util.Collections.unmodifiableList(featuredProducts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.featuredProducts_ = featuredProducts_;
      } else {
        result.featuredProducts_ = featuredProductsBuilder_.build();
      }
      if (similarProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          similarProducts_ = java.util.Collections.unmodifiableList(similarProducts_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.similarProducts_ = similarProducts_;
      } else {
        result.similarProducts_ = similarProductsBuilder_.build();
      }
      if (recentlyViewedProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          recentlyViewedProducts_ = java.util.Collections.unmodifiableList(recentlyViewedProducts_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.recentlyViewedProducts_ = recentlyViewedProducts_;
      } else {
        result.recentlyViewedProducts_ = recentlyViewedProductsBuilder_.build();
      }
      if (categoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          categories_ = java.util.Collections.unmodifiableList(categories_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.categories_ = categories_;
      } else {
        result.categories_ = categoriesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.in.dashboard.DashboardDetails) {
        return mergeFrom((com.in.dashboard.DashboardDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.in.dashboard.DashboardDetails other) {
      if (other == com.in.dashboard.DashboardDetails.getDefaultInstance()) return this;
      if (featuredProductsBuilder_ == null) {
        if (!other.featuredProducts_.isEmpty()) {
          if (featuredProducts_.isEmpty()) {
            featuredProducts_ = other.featuredProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeaturedProductsIsMutable();
            featuredProducts_.addAll(other.featuredProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.featuredProducts_.isEmpty()) {
          if (featuredProductsBuilder_.isEmpty()) {
            featuredProductsBuilder_.dispose();
            featuredProductsBuilder_ = null;
            featuredProducts_ = other.featuredProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            featuredProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFeaturedProductsFieldBuilder() : null;
          } else {
            featuredProductsBuilder_.addAllMessages(other.featuredProducts_);
          }
        }
      }
      if (similarProductsBuilder_ == null) {
        if (!other.similarProducts_.isEmpty()) {
          if (similarProducts_.isEmpty()) {
            similarProducts_ = other.similarProducts_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSimilarProductsIsMutable();
            similarProducts_.addAll(other.similarProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.similarProducts_.isEmpty()) {
          if (similarProductsBuilder_.isEmpty()) {
            similarProductsBuilder_.dispose();
            similarProductsBuilder_ = null;
            similarProducts_ = other.similarProducts_;
            bitField0_ = (bitField0_ & ~0x00000002);
            similarProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSimilarProductsFieldBuilder() : null;
          } else {
            similarProductsBuilder_.addAllMessages(other.similarProducts_);
          }
        }
      }
      if (recentlyViewedProductsBuilder_ == null) {
        if (!other.recentlyViewedProducts_.isEmpty()) {
          if (recentlyViewedProducts_.isEmpty()) {
            recentlyViewedProducts_ = other.recentlyViewedProducts_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRecentlyViewedProductsIsMutable();
            recentlyViewedProducts_.addAll(other.recentlyViewedProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.recentlyViewedProducts_.isEmpty()) {
          if (recentlyViewedProductsBuilder_.isEmpty()) {
            recentlyViewedProductsBuilder_.dispose();
            recentlyViewedProductsBuilder_ = null;
            recentlyViewedProducts_ = other.recentlyViewedProducts_;
            bitField0_ = (bitField0_ & ~0x00000004);
            recentlyViewedProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecentlyViewedProductsFieldBuilder() : null;
          } else {
            recentlyViewedProductsBuilder_.addAllMessages(other.recentlyViewedProducts_);
          }
        }
      }
      if (categoriesBuilder_ == null) {
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
      } else {
        if (!other.categories_.isEmpty()) {
          if (categoriesBuilder_.isEmpty()) {
            categoriesBuilder_.dispose();
            categoriesBuilder_ = null;
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000008);
            categoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCategoriesFieldBuilder() : null;
          } else {
            categoriesBuilder_.addAllMessages(other.categories_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.in.dashboard.DashboardDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.in.dashboard.DashboardDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.in.dashboard.Product> featuredProducts_ =
      java.util.Collections.emptyList();
    private void ensureFeaturedProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        featuredProducts_ = new java.util.ArrayList<com.in.dashboard.Product>(featuredProducts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> featuredProductsBuilder_;

    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public java.util.List<com.in.dashboard.Product> getFeaturedProductsList() {
      if (featuredProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(featuredProducts_);
      } else {
        return featuredProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public int getFeaturedProductsCount() {
      if (featuredProductsBuilder_ == null) {
        return featuredProducts_.size();
      } else {
        return featuredProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public com.in.dashboard.Product getFeaturedProducts(int index) {
      if (featuredProductsBuilder_ == null) {
        return featuredProducts_.get(index);
      } else {
        return featuredProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder setFeaturedProducts(
        int index, com.in.dashboard.Product value) {
      if (featuredProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturedProductsIsMutable();
        featuredProducts_.set(index, value);
        onChanged();
      } else {
        featuredProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder setFeaturedProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (featuredProductsBuilder_ == null) {
        ensureFeaturedProductsIsMutable();
        featuredProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        featuredProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder addFeaturedProducts(com.in.dashboard.Product value) {
      if (featuredProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturedProductsIsMutable();
        featuredProducts_.add(value);
        onChanged();
      } else {
        featuredProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder addFeaturedProducts(
        int index, com.in.dashboard.Product value) {
      if (featuredProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturedProductsIsMutable();
        featuredProducts_.add(index, value);
        onChanged();
      } else {
        featuredProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder addFeaturedProducts(
        com.in.dashboard.Product.Builder builderForValue) {
      if (featuredProductsBuilder_ == null) {
        ensureFeaturedProductsIsMutable();
        featuredProducts_.add(builderForValue.build());
        onChanged();
      } else {
        featuredProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder addFeaturedProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (featuredProductsBuilder_ == null) {
        ensureFeaturedProductsIsMutable();
        featuredProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        featuredProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder addAllFeaturedProducts(
        java.lang.Iterable<? extends com.in.dashboard.Product> values) {
      if (featuredProductsBuilder_ == null) {
        ensureFeaturedProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, featuredProducts_);
        onChanged();
      } else {
        featuredProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder clearFeaturedProducts() {
      if (featuredProductsBuilder_ == null) {
        featuredProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        featuredProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public Builder removeFeaturedProducts(int index) {
      if (featuredProductsBuilder_ == null) {
        ensureFeaturedProductsIsMutable();
        featuredProducts_.remove(index);
        onChanged();
      } else {
        featuredProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public com.in.dashboard.Product.Builder getFeaturedProductsBuilder(
        int index) {
      return getFeaturedProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public com.in.dashboard.ProductOrBuilder getFeaturedProductsOrBuilder(
        int index) {
      if (featuredProductsBuilder_ == null) {
        return featuredProducts_.get(index);  } else {
        return featuredProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
         getFeaturedProductsOrBuilderList() {
      if (featuredProductsBuilder_ != null) {
        return featuredProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(featuredProducts_);
      }
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public com.in.dashboard.Product.Builder addFeaturedProductsBuilder() {
      return getFeaturedProductsFieldBuilder().addBuilder(
          com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public com.in.dashboard.Product.Builder addFeaturedProductsBuilder(
        int index) {
      return getFeaturedProductsFieldBuilder().addBuilder(
          index, com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product featuredProducts = 1;</code>
     */
    public java.util.List<com.in.dashboard.Product.Builder> 
         getFeaturedProductsBuilderList() {
      return getFeaturedProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> 
        getFeaturedProductsFieldBuilder() {
      if (featuredProductsBuilder_ == null) {
        featuredProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder>(
                featuredProducts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        featuredProducts_ = null;
      }
      return featuredProductsBuilder_;
    }

    private java.util.List<com.in.dashboard.Product> similarProducts_ =
      java.util.Collections.emptyList();
    private void ensureSimilarProductsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        similarProducts_ = new java.util.ArrayList<com.in.dashboard.Product>(similarProducts_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> similarProductsBuilder_;

    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public java.util.List<com.in.dashboard.Product> getSimilarProductsList() {
      if (similarProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(similarProducts_);
      } else {
        return similarProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public int getSimilarProductsCount() {
      if (similarProductsBuilder_ == null) {
        return similarProducts_.size();
      } else {
        return similarProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public com.in.dashboard.Product getSimilarProducts(int index) {
      if (similarProductsBuilder_ == null) {
        return similarProducts_.get(index);
      } else {
        return similarProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder setSimilarProducts(
        int index, com.in.dashboard.Product value) {
      if (similarProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimilarProductsIsMutable();
        similarProducts_.set(index, value);
        onChanged();
      } else {
        similarProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder setSimilarProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (similarProductsBuilder_ == null) {
        ensureSimilarProductsIsMutable();
        similarProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        similarProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder addSimilarProducts(com.in.dashboard.Product value) {
      if (similarProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimilarProductsIsMutable();
        similarProducts_.add(value);
        onChanged();
      } else {
        similarProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder addSimilarProducts(
        int index, com.in.dashboard.Product value) {
      if (similarProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimilarProductsIsMutable();
        similarProducts_.add(index, value);
        onChanged();
      } else {
        similarProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder addSimilarProducts(
        com.in.dashboard.Product.Builder builderForValue) {
      if (similarProductsBuilder_ == null) {
        ensureSimilarProductsIsMutable();
        similarProducts_.add(builderForValue.build());
        onChanged();
      } else {
        similarProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder addSimilarProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (similarProductsBuilder_ == null) {
        ensureSimilarProductsIsMutable();
        similarProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        similarProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder addAllSimilarProducts(
        java.lang.Iterable<? extends com.in.dashboard.Product> values) {
      if (similarProductsBuilder_ == null) {
        ensureSimilarProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, similarProducts_);
        onChanged();
      } else {
        similarProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder clearSimilarProducts() {
      if (similarProductsBuilder_ == null) {
        similarProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        similarProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public Builder removeSimilarProducts(int index) {
      if (similarProductsBuilder_ == null) {
        ensureSimilarProductsIsMutable();
        similarProducts_.remove(index);
        onChanged();
      } else {
        similarProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public com.in.dashboard.Product.Builder getSimilarProductsBuilder(
        int index) {
      return getSimilarProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public com.in.dashboard.ProductOrBuilder getSimilarProductsOrBuilder(
        int index) {
      if (similarProductsBuilder_ == null) {
        return similarProducts_.get(index);  } else {
        return similarProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
         getSimilarProductsOrBuilderList() {
      if (similarProductsBuilder_ != null) {
        return similarProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(similarProducts_);
      }
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public com.in.dashboard.Product.Builder addSimilarProductsBuilder() {
      return getSimilarProductsFieldBuilder().addBuilder(
          com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public com.in.dashboard.Product.Builder addSimilarProductsBuilder(
        int index) {
      return getSimilarProductsFieldBuilder().addBuilder(
          index, com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product similarProducts = 2;</code>
     */
    public java.util.List<com.in.dashboard.Product.Builder> 
         getSimilarProductsBuilderList() {
      return getSimilarProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> 
        getSimilarProductsFieldBuilder() {
      if (similarProductsBuilder_ == null) {
        similarProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder>(
                similarProducts_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        similarProducts_ = null;
      }
      return similarProductsBuilder_;
    }

    private java.util.List<com.in.dashboard.Product> recentlyViewedProducts_ =
      java.util.Collections.emptyList();
    private void ensureRecentlyViewedProductsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        recentlyViewedProducts_ = new java.util.ArrayList<com.in.dashboard.Product>(recentlyViewedProducts_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> recentlyViewedProductsBuilder_;

    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public java.util.List<com.in.dashboard.Product> getRecentlyViewedProductsList() {
      if (recentlyViewedProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recentlyViewedProducts_);
      } else {
        return recentlyViewedProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public int getRecentlyViewedProductsCount() {
      if (recentlyViewedProductsBuilder_ == null) {
        return recentlyViewedProducts_.size();
      } else {
        return recentlyViewedProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public com.in.dashboard.Product getRecentlyViewedProducts(int index) {
      if (recentlyViewedProductsBuilder_ == null) {
        return recentlyViewedProducts_.get(index);
      } else {
        return recentlyViewedProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder setRecentlyViewedProducts(
        int index, com.in.dashboard.Product value) {
      if (recentlyViewedProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.set(index, value);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder setRecentlyViewedProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (recentlyViewedProductsBuilder_ == null) {
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder addRecentlyViewedProducts(com.in.dashboard.Product value) {
      if (recentlyViewedProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.add(value);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder addRecentlyViewedProducts(
        int index, com.in.dashboard.Product value) {
      if (recentlyViewedProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.add(index, value);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder addRecentlyViewedProducts(
        com.in.dashboard.Product.Builder builderForValue) {
      if (recentlyViewedProductsBuilder_ == null) {
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.add(builderForValue.build());
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder addRecentlyViewedProducts(
        int index, com.in.dashboard.Product.Builder builderForValue) {
      if (recentlyViewedProductsBuilder_ == null) {
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder addAllRecentlyViewedProducts(
        java.lang.Iterable<? extends com.in.dashboard.Product> values) {
      if (recentlyViewedProductsBuilder_ == null) {
        ensureRecentlyViewedProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recentlyViewedProducts_);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder clearRecentlyViewedProducts() {
      if (recentlyViewedProductsBuilder_ == null) {
        recentlyViewedProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public Builder removeRecentlyViewedProducts(int index) {
      if (recentlyViewedProductsBuilder_ == null) {
        ensureRecentlyViewedProductsIsMutable();
        recentlyViewedProducts_.remove(index);
        onChanged();
      } else {
        recentlyViewedProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public com.in.dashboard.Product.Builder getRecentlyViewedProductsBuilder(
        int index) {
      return getRecentlyViewedProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public com.in.dashboard.ProductOrBuilder getRecentlyViewedProductsOrBuilder(
        int index) {
      if (recentlyViewedProductsBuilder_ == null) {
        return recentlyViewedProducts_.get(index);  } else {
        return recentlyViewedProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public java.util.List<? extends com.in.dashboard.ProductOrBuilder> 
         getRecentlyViewedProductsOrBuilderList() {
      if (recentlyViewedProductsBuilder_ != null) {
        return recentlyViewedProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recentlyViewedProducts_);
      }
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public com.in.dashboard.Product.Builder addRecentlyViewedProductsBuilder() {
      return getRecentlyViewedProductsFieldBuilder().addBuilder(
          com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public com.in.dashboard.Product.Builder addRecentlyViewedProductsBuilder(
        int index) {
      return getRecentlyViewedProductsFieldBuilder().addBuilder(
          index, com.in.dashboard.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product recentlyViewedProducts = 3;</code>
     */
    public java.util.List<com.in.dashboard.Product.Builder> 
         getRecentlyViewedProductsBuilderList() {
      return getRecentlyViewedProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder> 
        getRecentlyViewedProductsFieldBuilder() {
      if (recentlyViewedProductsBuilder_ == null) {
        recentlyViewedProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.in.dashboard.Product, com.in.dashboard.Product.Builder, com.in.dashboard.ProductOrBuilder>(
                recentlyViewedProducts_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        recentlyViewedProducts_ = null;
      }
      return recentlyViewedProductsBuilder_;
    }

    private java.util.List<com.in.dashboard.Category> categories_ =
      java.util.Collections.emptyList();
    private void ensureCategoriesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        categories_ = new java.util.ArrayList<com.in.dashboard.Category>(categories_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Category, com.in.dashboard.Category.Builder, com.in.dashboard.CategoryOrBuilder> categoriesBuilder_;

    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public java.util.List<com.in.dashboard.Category> getCategoriesList() {
      if (categoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(categories_);
      } else {
        return categoriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public int getCategoriesCount() {
      if (categoriesBuilder_ == null) {
        return categories_.size();
      } else {
        return categoriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public com.in.dashboard.Category getCategories(int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);
      } else {
        return categoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder setCategories(
        int index, com.in.dashboard.Category value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder setCategories(
        int index, com.in.dashboard.Category.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.set(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder addCategories(com.in.dashboard.Category value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder addCategories(
        int index, com.in.dashboard.Category value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(index, value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder addCategories(
        com.in.dashboard.Category.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder addCategories(
        int index, com.in.dashboard.Category.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder addAllCategories(
        java.lang.Iterable<? extends com.in.dashboard.Category> values) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categories_);
        onChanged();
      } else {
        categoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder clearCategories() {
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        categoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public Builder removeCategories(int index) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.remove(index);
        onChanged();
      } else {
        categoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public com.in.dashboard.Category.Builder getCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public com.in.dashboard.CategoryOrBuilder getCategoriesOrBuilder(
        int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);  } else {
        return categoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public java.util.List<? extends com.in.dashboard.CategoryOrBuilder> 
         getCategoriesOrBuilderList() {
      if (categoriesBuilder_ != null) {
        return categoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(categories_);
      }
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public com.in.dashboard.Category.Builder addCategoriesBuilder() {
      return getCategoriesFieldBuilder().addBuilder(
          com.in.dashboard.Category.getDefaultInstance());
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public com.in.dashboard.Category.Builder addCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().addBuilder(
          index, com.in.dashboard.Category.getDefaultInstance());
    }
    /**
     * <code>repeated .Category categories = 4;</code>
     */
    public java.util.List<com.in.dashboard.Category.Builder> 
         getCategoriesBuilderList() {
      return getCategoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.in.dashboard.Category, com.in.dashboard.Category.Builder, com.in.dashboard.CategoryOrBuilder> 
        getCategoriesFieldBuilder() {
      if (categoriesBuilder_ == null) {
        categoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.in.dashboard.Category, com.in.dashboard.Category.Builder, com.in.dashboard.CategoryOrBuilder>(
                categories_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        categories_ = null;
      }
      return categoriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DashboardDetails)
  }

  // @@protoc_insertion_point(class_scope:DashboardDetails)
  private static final com.in.dashboard.DashboardDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.in.dashboard.DashboardDetails();
  }

  public static com.in.dashboard.DashboardDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DashboardDetails>
      PARSER = new com.google.protobuf.AbstractParser<DashboardDetails>() {
    @java.lang.Override
    public DashboardDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DashboardDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DashboardDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DashboardDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.in.dashboard.DashboardDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

