// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dashboard.proto

package com.in.dashboard;

public final class Dashboard {
  private Dashboard() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DashboardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DashboardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DashboardDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DashboardDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DashboardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DashboardResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewCartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Dashboard.proto\"%\n\020DashboardRequest\022\021\n" +
      "\tproductId\030\001 \003(\t\"\203\001\n\007Product\022\021\n\tproductI" +
      "d\030\001 \001(\t\022\022\n\ncategoryId\030\002 \001(\t\022\023\n\013productNa" +
      "me\030\003 \001(\t\022\023\n\013productDesc\030\004 \001(\t\022\024\n\014product" +
      "Price\030\005 \001(\001\022\021\n\timagePath\030\006 \001(\t\"G\n\010Catego" +
      "ry\022\022\n\ncategoryId\030\001 \001(\t\022\024\n\014categoryName\030\002" +
      " \001(\t\022\021\n\timagePath\030\003 \001(\t\"\242\001\n\020DashboardDet" +
      "ails\022\"\n\020featuredProducts\030\001 \003(\0132\010.Product" +
      "\022!\n\017similarProducts\030\002 \003(\0132\010.Product\022(\n\026r" +
      "ecentlyViewedProducts\030\003 \003(\0132\010.Product\022\035\n" +
      "\ncategories\030\004 \003(\0132\t.Category\"@\n\021Dashboar" +
      "dResponse\022+\n\020dashBoardDetails\030\001 \001(\0132\021.Da" +
      "shboardDetails\"\'\n\022ProductDataRequest\022\021\n\t" +
      "productId\030\001 \001(\t\"S\n\023ProductDataResponse\022\031" +
      "\n\007product\030\001 \001(\0132\010.Product\022!\n\017similarProd" +
      "ucts\030\002 \003(\0132\010.Product\"\201\001\n\024FilterProductRe" +
      "quest\022\022\n\ncategoryId\030\001 \001(\t\022,\n\006filter\030\002 \001(" +
      "\0162\034.FilterProductRequest.Filter\"\'\n\006Filte" +
      "r\022\005\n\001P\020\000\022\006\n\002LH\020\001\022\006\n\002HL\020\002\022\006\n\002NF\020\003\"2\n\025Filt" +
      "erProductResponse\022\031\n\007product\030\001 \003(\0132\010.Pro" +
      "duct\"-\n\020ViewCartResponse\022\031\n\007product\030\001 \003(" +
      "\0132\010.Product2\234\002\n\027ProductDashboardService\022" +
      "A\n\030fetchProductForDashboard\022\021.DashboardR" +
      "equest\032\022.DashboardResponse\022@\n\023fetchProdu" +
      "ctDetails\022\023.ProductDataRequest\032\024.Product" +
      "DataResponse\022B\n\021filterProductData\022\025.Filt" +
      "erProductRequest\032\026.FilterProductResponse" +
      "\0228\n\020addProductToCart\022\021.DashboardRequest\032" +
      "\021.ViewCartResponseB\024\n\020com.in.dashboardP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DashboardRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DashboardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DashboardRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "ProductId", "CategoryId", "ProductName", "ProductDesc", "ProductPrice", "ImagePath", });
    internal_static_Category_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Category_descriptor,
        new java.lang.String[] { "CategoryId", "CategoryName", "ImagePath", });
    internal_static_DashboardDetails_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DashboardDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DashboardDetails_descriptor,
        new java.lang.String[] { "FeaturedProducts", "SimilarProducts", "RecentlyViewedProducts", "Categories", });
    internal_static_DashboardResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DashboardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DashboardResponse_descriptor,
        new java.lang.String[] { "DashBoardDetails", });
    internal_static_ProductDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ProductDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductDataRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_ProductDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ProductDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductDataResponse_descriptor,
        new java.lang.String[] { "Product", "SimilarProducts", });
    internal_static_FilterProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_FilterProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterProductRequest_descriptor,
        new java.lang.String[] { "CategoryId", "Filter", });
    internal_static_FilterProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_FilterProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterProductResponse_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_ViewCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ViewCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ViewCartResponse_descriptor,
        new java.lang.String[] { "Product", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
