// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dashboard.proto

package com.in.dashboard;

public interface ProductDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
