server:
  port: 8080

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    kafka: INFO
    io.confluent.kafka.serializers: INFO
    io.confluent.kafka.schemaregistry: INFO
    io.confluent.kafka.schemaregistry.client: INFO
    io.confluent.kafka.schemaregistry.client.rest: INFO
  config: classpath:log4j2.xml