/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.in.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6673726906430604101L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductDetails\",\"namespace\":\"com.in.avro\",\"fields\":[{\"name\":\"categoryId\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"productDescription\",\"type\":\"string\"},{\"name\":\"productPrice\",\"type\":\"double\"},{\"name\":\"date\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"imagePath\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductDetails> ENCODER =
      new BinaryMessageEncoder<ProductDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductDetails> DECODER =
      new BinaryMessageDecoder<ProductDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductDetails>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence categoryId;
   private java.lang.CharSequence productName;
   private java.lang.CharSequence productDescription;
   private double productPrice;
   private java.time.Instant date;
   private java.lang.CharSequence imagePath;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductDetails() {}

  /**
   * All-args constructor.
   * @param categoryId The new value for categoryId
   * @param productName The new value for productName
   * @param productDescription The new value for productDescription
   * @param productPrice The new value for productPrice
   * @param date The new value for date
   * @param imagePath The new value for imagePath
   */
  public ProductDetails(java.lang.CharSequence categoryId, java.lang.CharSequence productName, java.lang.CharSequence productDescription, java.lang.Double productPrice, java.time.Instant date, java.lang.CharSequence imagePath) {
    this.categoryId = categoryId;
    this.productName = productName;
    this.productDescription = productDescription;
    this.productPrice = productPrice;
    this.date = date.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.imagePath = imagePath;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return categoryId;
    case 1: return productName;
    case 2: return productDescription;
    case 3: return productPrice;
    case 4: return date;
    case 5: return imagePath;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: categoryId = (java.lang.CharSequence)value$; break;
    case 1: productName = (java.lang.CharSequence)value$; break;
    case 2: productDescription = (java.lang.CharSequence)value$; break;
    case 3: productPrice = (java.lang.Double)value$; break;
    case 4: date = (java.time.Instant)value$; break;
    case 5: imagePath = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'categoryId' field.
   * @return The value of the 'categoryId' field.
   */
  public java.lang.CharSequence getCategoryId() {
    return categoryId;
  }


  /**
   * Sets the value of the 'categoryId' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.lang.CharSequence value) {
    this.categoryId = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'productDescription' field.
   * @return The value of the 'productDescription' field.
   */
  public java.lang.CharSequence getProductDescription() {
    return productDescription;
  }


  /**
   * Sets the value of the 'productDescription' field.
   * @param value the value to set.
   */
  public void setProductDescription(java.lang.CharSequence value) {
    this.productDescription = value;
  }

  /**
   * Gets the value of the 'productPrice' field.
   * @return The value of the 'productPrice' field.
   */
  public double getProductPrice() {
    return productPrice;
  }


  /**
   * Sets the value of the 'productPrice' field.
   * @param value the value to set.
   */
  public void setProductPrice(double value) {
    this.productPrice = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.Instant getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.Instant value) {
    this.date = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'imagePath' field.
   * @return The value of the 'imagePath' field.
   */
  public java.lang.CharSequence getImagePath() {
    return imagePath;
  }


  /**
   * Sets the value of the 'imagePath' field.
   * @param value the value to set.
   */
  public void setImagePath(java.lang.CharSequence value) {
    this.imagePath = value;
  }

  /**
   * Creates a new ProductDetails RecordBuilder.
   * @return A new ProductDetails RecordBuilder
   */
  public static com.in.avro.ProductDetails.Builder newBuilder() {
    return new com.in.avro.ProductDetails.Builder();
  }

  /**
   * Creates a new ProductDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductDetails RecordBuilder
   */
  public static com.in.avro.ProductDetails.Builder newBuilder(com.in.avro.ProductDetails.Builder other) {
    if (other == null) {
      return new com.in.avro.ProductDetails.Builder();
    } else {
      return new com.in.avro.ProductDetails.Builder(other);
    }
  }

  /**
   * Creates a new ProductDetails RecordBuilder by copying an existing ProductDetails instance.
   * @param other The existing instance to copy.
   * @return A new ProductDetails RecordBuilder
   */
  public static com.in.avro.ProductDetails.Builder newBuilder(com.in.avro.ProductDetails other) {
    if (other == null) {
      return new com.in.avro.ProductDetails.Builder();
    } else {
      return new com.in.avro.ProductDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductDetails>
    implements org.apache.avro.data.RecordBuilder<ProductDetails> {

    private java.lang.CharSequence categoryId;
    private java.lang.CharSequence productName;
    private java.lang.CharSequence productDescription;
    private double productPrice;
    private java.time.Instant date;
    private java.lang.CharSequence imagePath;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.in.avro.ProductDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[0].schema(), other.categoryId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[2].schema(), other.productDescription);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[3].schema(), other.productPrice);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.date)) {
        this.date = data().deepCopy(fields()[4].schema(), other.date);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.imagePath)) {
        this.imagePath = data().deepCopy(fields()[5].schema(), other.imagePath);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.in.avro.ProductDetails other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[0].schema(), other.categoryId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[2].schema(), other.productDescription);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[3].schema(), other.productPrice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.date)) {
        this.date = data().deepCopy(fields()[4].schema(), other.date);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.imagePath)) {
        this.imagePath = data().deepCopy(fields()[5].schema(), other.imagePath);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'categoryId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryId() {
      return categoryId;
    }


    /**
      * Sets the value of the 'categoryId' field.
      * @param value The value of 'categoryId'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setCategoryId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.categoryId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryId' field has been set.
      * @return True if the 'categoryId' field has been set, false otherwise.
      */
    public boolean hasCategoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'categoryId' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearCategoryId() {
      categoryId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.productName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductDescription() {
      return productDescription;
    }


    /**
      * Sets the value of the 'productDescription' field.
      * @param value The value of 'productDescription'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setProductDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.productDescription = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productDescription' field has been set.
      * @return True if the 'productDescription' field has been set, false otherwise.
      */
    public boolean hasProductDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productDescription' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearProductDescription() {
      productDescription = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productPrice' field.
      * @return The value.
      */
    public double getProductPrice() {
      return productPrice;
    }


    /**
      * Sets the value of the 'productPrice' field.
      * @param value The value of 'productPrice'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setProductPrice(double value) {
      validate(fields()[3], value);
      this.productPrice = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productPrice' field has been set.
      * @return True if the 'productPrice' field has been set, false otherwise.
      */
    public boolean hasProductPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productPrice' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearProductPrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.Instant getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setDate(java.time.Instant value) {
      validate(fields()[4], value);
      this.date = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearDate() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'imagePath' field.
      * @return The value.
      */
    public java.lang.CharSequence getImagePath() {
      return imagePath;
    }


    /**
      * Sets the value of the 'imagePath' field.
      * @param value The value of 'imagePath'.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder setImagePath(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.imagePath = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'imagePath' field has been set.
      * @return True if the 'imagePath' field has been set, false otherwise.
      */
    public boolean hasImagePath() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'imagePath' field.
      * @return This builder.
      */
    public com.in.avro.ProductDetails.Builder clearImagePath() {
      imagePath = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductDetails build() {
      try {
        ProductDetails record = new ProductDetails();
        record.categoryId = fieldSetFlags()[0] ? this.categoryId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productName = fieldSetFlags()[1] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.productDescription = fieldSetFlags()[2] ? this.productDescription : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.productPrice = fieldSetFlags()[3] ? this.productPrice : (java.lang.Double) defaultValue(fields()[3]);
        record.date = fieldSetFlags()[4] ? this.date : (java.time.Instant) defaultValue(fields()[4]);
        record.imagePath = fieldSetFlags()[5] ? this.imagePath : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductDetails>
    READER$ = (org.apache.avro.io.DatumReader<ProductDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










